apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-chatbot
  labels:
    app: discord-chatbot
spec:
  selector:
    matchLabels:
      app: discord-chatbot
  replicas: 2
  template:
    metadata:
      labels:
        app: discord-chatbot
    spec:
      containers:
        - name: discord-chatbot
          image: codekulkarni/discord-chatbot
          imagePullPolicy: Always
          env:
            - name: DISCORD
              value: 'NzYxODg2MzA2MDQ5NDU4MjA3.X3hH6g.7wvjBWviiCU4dcYQZ5Xr-QCJCQU'
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: discord-chatbot
  labels:
    app: discord-chatbot
spec:
  type: LoadBalancer
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 3000
      name: http
  selector:
    app: discord-chatbot
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: discord-chatbot
#   labels:
#     app: discord-chatbot
# spec:
#   type: ClusterIP
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 3000
#       name: http
#   selector:
#     app: discord-chatbot

# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: discord-chatbot
# spec:
#   rules:
#     - host: sgkul2000.cloud.okteto.net
#       http:
#         paths:
#           - path: /
#             backend:
#               serviceName: discord-chatbot
#               servicePort: 80
